Repository jetstack/jetstack-secure, pull requests merged in 2020-07, with the labels that each got.

#180 Adds write-to-file flag to store data locally
  cmd/agent.go
  pkg/agent/run.go
Labels: approved, dco-signoff: yes, lgtm, size/M

#182 Flag: input-path
  cmd/agent.go
  pkg/agent/run.go
Labels: approved, dco-signoff: yes, lgtm, size/S

#183 Input/Output Path added to agent.yaml
  pkg/agent/config.go
  pkg/agent/config_test.go
  pkg/agent/run.go
Labels: approved, dco-signoff: yes, lgtm, size/S

#187 Use static linking
  Makefile
Labels: approved, dco-signoff: yes, lgtm, size/XS

#185 Edits data gathering process to retry dataGatherer
  agent.yaml
  cmd/agent.go
  go.mod
  go.sum
  pkg/agent/config_test.go
  pkg/agent/dummy_data_gatherer.go
  pkg/agent/run.go
Labels: approved, dco-signoff: yes, lgtm, size/L

#190 exp backoff fails when datagatherers have no error
  pkg/agent/run.go
Labels: approved, dco-signoff: yes, lgtm, size/S

#189 Retain certs when posting tls secrets
  docs/datagatherers/k8s-dynamic.md
  pkg/datagatherer/k8s/dynamic.go
  pkg/datagatherer/k8s/dynamic_test.go
Labels: approved, dco-signoff: yes, lgtm, size/M

#191 Remove not useful issue templates
  .github/ISSUE_TEMPLATE/document-research.md
  .github/ISSUE_TEMPLATE/package-suggestion.md
  .github/ISSUE_TEMPLATE/user-story.md
Labels: approved, dco-signoff: yes, lgtm, size/L

#192 Update gke package configuration docs
  docs/datagatherers/gke.md
Labels: approved, dco-signoff: yes, documentation, lgtm, size/XS

#193 Add Olu to approvers list
  OWNERS
Labels: approved, dco-signoff: yes, lgtm, size/XS

#194 Increased backoff time for repeated login attempts
  cmd/agent.go
  pkg/agent/run.go
Labels: approved, dco-signoff: yes, lgtm, size/XS
