Repository jetstack/jetstack-secure, pull requests merged in 2020-03, with the labels that each got.

#131 Readme check disclaimer
  README.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#130 Kubernetes data gatherer exclude some namespaces
  examples/pods.preflight.yaml
  internal/checkconfig/checkconfig.go
  pkg/datagatherer/k8s/generic.go
  pkg/datagatherer/k8s/generic_test.go
Labels: approved, dco-signoff: yes, lgtm, size/L

#134 Use non interactive client loading rules
  pkg/datagatherer/k8s/client.go
Labels: approved, dco-signoff: yes, lgtm, size/S

#133 Redact Kubernetes Secret data
  pkg/datagatherer/k8s/generic.go
  pkg/datagatherer/k8s/generic_test.go
Labels: approved, dco-signoff: yes, lgtm, size/M

#136 Fix secret redaction group check to change Core to core
  pkg/datagatherer/k8s/generic.go
Labels: approved, dco-signoff: yes, lgtm, size/XS

#135 Agent installation docs
  README.md
  deprecated-check-examples/aks.preflight.yaml
  deprecated-check-examples/gke.preflight.yaml
  deprecated-check-examples/pods.preflight.yaml
  deprecated-check-examples/reports/gke.json
  deprecated-check-examples/reports/pods.json
  deprecated-check-examples/stubbed.preflight.yaml
  docs/check.md
  docs/configuration.md
  docs/installation_manual_in_cluster.md
Labels: approved, dco-signoff: yes, lgtm, size/XL

#138 Support providing auth token in cli flag
  cmd/agent.go
  pkg/agent/run.go
Labels: approved, dco-signoff: yes, lgtm, size/S

#139 Fail if auth token is not present.
  pkg/agent/run.go
Labels: approved, dco-signoff: yes, lgtm, size/XS

#140 Add agent config instead of old config
  Dockerfile
Labels: approved, dco-signoff: yes, lgtm, size/XS

#142 Fix some missing references to deprecated examples
  Makefile
  docs/check.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#143 Fix bundle creation
  Makefile
Labels: approved, dco-signoff: yes, lgtm, size/XS

#141 Bind env variables to config flags
  cmd/root.go
  go.mod
Labels: approved, dco-signoff: yes, size/S

#145 Use better defaults for config file
  agent.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#144 Add period flag
  cmd/agent.go
  pkg/agent/run.go
Labels: approved, dco-signoff: yes, size/S

#146 Add james-w to OWNERS
  OWNERS
Labels: approved, dco-signoff: yes, lgtm, size/XS

#152 Redact the last applied configuration annotation
  pkg/datagatherer/k8s/generic.go
  pkg/datagatherer/k8s/generic_test.go
Labels: approved, dco-signoff: yes, lgtm, size/M
