Repository jetstack/jetstack-secure, pull requests merged in 2020-11, with the labels that each got.

#200 Add Version Checker datagatherer
  go.mod
  go.sum
  pkg/agent/config.go
  pkg/datagatherer/versionchecker/fixtures/example_host
  pkg/datagatherer/versionchecker/fixtures/example_host_2
  pkg/datagatherer/versionchecker/fixtures/example_secret
  pkg/datagatherer/versionchecker/fixtures/manifest-100.json
  pkg/datagatherer/versionchecker/fixtures/manifest-101.json
  pkg/datagatherer/versionchecker/fixtures/pods.json.tmpl
  pkg/datagatherer/versionchecker/fixtures/tags.json
  pkg/datagatherer/versionchecker/versionchecker.go
  pkg/datagatherer/versionchecker/versionchecker_test.go
Labels: approved, dco-signoff: yes, do-not-merge/release-note-label-needed, size/XL

#201 Remove last-applied... annotation from metadata
  pkg/datagatherer/k8s/dynamic.go
  pkg/datagatherer/k8s/dynamic_test.go
Labels: approved, dco-signoff: yes, do-not-merge/release-note-label-needed, lgtm, size/M

#203 Remove managed fields
  go.mod
  go.sum
  pkg/datagatherer/k8s/dynamic.go
  pkg/datagatherer/k8s/dynamic_test.go
Labels: approved, dco-signoff: yes, do-not-merge/release-note-label-needed, lgtm, size/L

#204 Implement more generic means of filtering uploaded objects
  go.mod
  go.sum
  pkg/datagatherer/k8s/dynamic.go
  pkg/datagatherer/k8s/dynamic_test.go
  pkg/datagatherer/k8s/fieldfilter.go
  pkg/datagatherer/k8s/fieldfilter_test.go
Labels: approved, dco-signoff: yes, do-not-merge/hold, do-not-merge/release-note-label-needed, size/L

#205 Correct last-applied-configuration annotations key
  pkg/datagatherer/k8s/fieldfilter.go
  pkg/datagatherer/k8s/fieldfilter_test.go
Labels: approved, dco-signoff: yes, do-not-merge/release-note-label-needed, lgtm, size/M

#206 Correct JSONPointer for redacting last-applied
  go.mod
  go.sum
  pkg/agent/run.go
  pkg/datagatherer/k8s/dynamic.go
  pkg/datagatherer/k8s/fieldfilter.go
Labels: approved, dco-signoff: yes, do-not-merge/release-note-label-needed, lgtm, size/S

#207 Make more prominent that only secrets are redacted
  docs/datagatherers/k8s-dynamic.md
Labels: approved, dco-signoff: yes, do-not-merge/release-note-label-needed, lgtm, size/S

#208 Add a test for filtering a non secret resource
  pkg/datagatherer/k8s/fieldfilter_test.go
Labels: approved, dco-signoff: yes, do-not-merge/release-note-label-needed, lgtm, size/M

#209 Send uid, selfLink and ownerReferences
  pkg/datagatherer/k8s/fieldfilter.go
Labels: approved, dco-signoff: yes, do-not-merge/release-note-label-needed, size/XS

#210 Update version checker data gatherer
  go.mod
  go.sum
  pkg/datagatherer/versionchecker/fixtures/manifest-100.json
  pkg/datagatherer/versionchecker/fixtures/manifest-101.json
  pkg/datagatherer/versionchecker/fixtures/nodes.json
  pkg/datagatherer/versionchecker/fixtures/pods.json.tmpl
  pkg/datagatherer/versionchecker/versionchecker.go
  pkg/datagatherer/versionchecker/versionchecker_test.go
Labels: approved, dco-signoff: yes, do-not-merge/hold, do-not-merge/release-note-label-needed, size/L
