Repository jetstack/jetstack-secure, pull requests merged in 2020-05, with the labels that each got.

#167 Refresh config, data per run (and allow partial data posting)
  pkg/agent/run.go
Labels: approved, dco-signoff: yes, lgtm, size/M

#166 Fix some issues for oauth2 client
  Makefile
  pkg/agent/run.go
  pkg/client/accessToken.go
  pkg/client/client.go
  pkg/client/credentials.go
Labels: approved, dco-signoff: yes, lgtm, size/M

#165 Implementation of k8s-discovery datagatherer
  docs/datagatherers/k8s-discovery.md
  docs/datagatherers/k8s-dynamic.md
  examples/cert-manager-agent.yaml
  pkg/agent/config.go
  pkg/datagatherer/k8s/client.go
  pkg/datagatherer/k8s/client_test.go
  pkg/datagatherer/k8s/discovery.go
  pkg/datagatherer/k8s/dynamic.go
  pkg/datagatherer/k8s/dynamic_test.go
Labels: approved, dco-signoff: yes, lgtm, size/L

#164 Check post data error
  pkg/agent/run.go
Labels: approved, dco-signoff: yes, lgtm, size/XS

#168 Add agent info command
  cmd/agent.go
  cmd/helpers.go
  cmd/version.go
Labels: approved, dco-signoff: yes, lgtm, size/M

#170 Catch missing OAuth2 credentials
  pkg/client/client.go
Labels: approved, dco-signoff: yes, lgtm, size/XS

#171 Log version to make debugging easier
  pkg/agent/run.go
Labels: approved, dco-signoff: yes, lgtm, size/XS

#172 Add OAuth2 configuration for preflight.jetstack.io
  Makefile
Labels: approved, dco-signoff: yes, lgtm, size/XS

#169 Pass oauth flags to docker build
  Dockerfile
  Makefile
Labels: approved, dco-signoff: yes, lgtm, size/S

#173 Fix make build
  Makefile
Labels: approved, dco-signoff: yes, size/XS

#174 Encode payload in POST to get access token
  pkg/client/accessToken.go
Labels: approved, dco-signoff: yes, size/S
