Repository jetstack/jetstack-secure, pull requests merged in 2020-04, with the labels that each got.

#154 Remove package guide
  docs/how_to_write_packages.md
Labels: approved, dco-signoff: yes, lgtm, size/L

#153 Remove preflight packages
  Dockerfile
  Makefile
  preflight-packages/examples.jetstack.io/aks_basic/aks.rego
  preflight-packages/examples.jetstack.io/aks_basic/aks_test.rego
  preflight-packages/examples.jetstack.io/aks_basic/policy-manifest.yaml
  preflight-packages/examples.jetstack.io/gke_basic/gke.rego
  preflight-packages/examples.jetstack.io/gke_basic/gke_test.rego
  preflight-packages/examples.jetstack.io/gke_basic/policy-manifest.yaml
  preflight-packages/jetstack.io/pods/pods.rego
  preflight-packages/jetstack.io/pods/pods_test.rego
  preflight-packages/jetstack.io/pods/policy-manifest.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XXL

#156 Scrape only Included namespaces when set to allow more restricted RBAC
  pkg/datagatherer/k8s/generic.go
  pkg/datagatherer/k8s/generic_test.go
Labels: approved, dco-signoff: yes, lgtm, size/L

#158 Show how to configure gke datagatherer permissions
  docs/datagatherers/gke.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#157 Add example cert-manager agent yaml
  examples/cert-manager-agent.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#159 Change agent to support OAuth2 auth
  Makefile
  cmd/agent.go
  pkg/agent/credentials.go
  pkg/agent/run.go
  pkg/client/accessToken.go
  pkg/client/client.go
Labels: approved, dco-signoff: yes, lgtm, size/L

#162 Add guide for GKE checks
  docs/guides/gke_local/guide.md
  docs/guides/gke_local/img/cluster.png
  docs/guides/gke_local/img/ready.png
  docs/guides/gke_local/img/release.png
  docs/guides/gke_local/img/select_token.png
Labels: approved, dco-signoff: yes, lgtm, size/L

#161 Fix bug with new preflight client and basic auth
  pkg/agent/run.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/S

#160 Fix GKE config in GKE data-gatherer doc
  docs/datagatherers/gke.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#163 Make agent support new endpoint for gathering data
  Makefile
  api/agent.go
  api/datareading.go
  pkg/agent/config.go
  pkg/agent/config_test.go
  pkg/agent/run.go
  pkg/client/client.go
  pkg/client/http.go
Labels: approved, dco-signoff: yes, lgtm, size/L
