Repository jetstack/jetstack-secure, pull requests merged in 2020-02, with the labels that each got.

#65 Add rules for node and pod affinity
  preflight-packages/jetstack.io/pods/pods.rego
  preflight-packages/jetstack.io/pods/pods_test.rego
  preflight-packages/jetstack.io/pods/policy-manifest.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#79 Fix typo in example AKS Preflight config
  examples/aks.preflight.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#81 Recreate enabledPackages slice so it is empty
  cmd/check.go
Labels: approved, dco-signoff: yes, lgtm, size/XS

#75 Update preflight.yamls to new config
  deployment/kubernetes/overlays/scanner/config/preflight.yaml
  examples/aks.preflight.yaml
  examples/gke.preflight.yaml
  examples/pods.preflight.yaml
Labels: approved, dco-signoff: yes, lgtm, size/S

#77 Don't mark manual rules without Rego as missing
  pkg/reports/reports.go
  pkg/reports/reports_test.go
Labels: approved, dco-signoff: yes, lgtm, size/S

#83 Data gatherers file
  cmd/check.go
  docs/configuration.md
  docs/datagatherers/local.md
  examples/data/aks.json
  examples/data/gke.json
  examples/stubbed.preflight.yaml
  pkg/datagatherer/local/local.go
Labels: approved, dco-signoff: yes, lgtm, size/L

#84 Add cluster and timestamp to summary
  cmd/check.go
Labels: approved, dco-signoff: yes, lgtm, size/XS

#89 Custom unmarshaler for ClusterSummary
  api/cluster.go
  api/cluster_test.go
Labels: approved, dco-signoff: yes, lgtm, size/L

#93 Return error on closing gcs write
  pkg/output/gcs/gcs.go
Labels: approved, dco-signoff: yes, lgtm, size/XS

#87 Add minimal version of the agent command
  cmd/agent.go
  cmd/root.go
  go.mod
  go.sum
  pkg/agent/config.go
  pkg/agent/config_test.go
  pkg/agent/run.go
Labels: approved, dco-signoff: yes, lgtm, size/L

#96 Make agent upload data
  agent.yaml
  api/datareading.go
  cmd/agent.go
  cmd/echo.go
  go.mod
  go.sum
  pkg/agent/config.go
  pkg/agent/config_test.go
  pkg/agent/run.go
Labels: approved, dco-signoff: yes, lgtm, size/L

#97 Add issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/document-research.md
  .github/ISSUE_TEMPLATE/package-suggestion.md
  .github/ISSUE_TEMPLATE/user-story.md
Labels: approved, dco-signoff: yes, lgtm, size/L

#98 Switch k8s/pod data gatherer to use the dynamic client
  cmd/check.go
  go.mod
  go.sum
  pkg/datagatherer/k8s/client.go
  pkg/datagatherer/k8s/generic.go
  pkg/datagatherer/k8s/generic_test.go
  pkg/datagatherer/k8s/pods.go
Labels: approved, dco-signoff: yes, lgtm, size/L

#99 Expose generic data gatherer through custom gatherer name format
  cmd/check.go
  pkg/datagatherer/k8s/generic.go
  pkg/datagatherer/k8s/generic_test.go
  pkg/datagatherer/k8s/pods.go
Labels: approved, dco-signoff: yes, lgtm, size/M

#100 Data gatherers config
  cmd/check.go
  pkg/datagatherer/aks/aks.go
  pkg/datagatherer/eks/eks.go
  pkg/datagatherer/gke/gke.go
  pkg/datagatherer/k8s/generic.go
  pkg/datagatherer/k8s/generic_test.go
  pkg/datagatherer/local/local.go
Labels: approved, dco-signoff: yes, lgtm, size/L

#102 Create pathutils package
  cmd/check.go
  pkg/pathutils/pathutils.go
Labels: approved, dco-signoff: yes, lgtm, size/M

#101 Refactor package source and package source config
  cmd/check.go
  cmd/test.go
  pkg/packagesources/local/local.go
  pkg/packagesources/packagesources.go
  pkg/packaging/eval.go
  pkg/packaging/packaging.go
  pkg/packaging/test.go
Labels: approved, dco-signoff: yes, lgtm, size/L

#103 Use DataGatherer constructors as functions for the config
  cmd/check.go
  pkg/datagatherer/aks/aks.go
  pkg/datagatherer/datagatherer.go
  pkg/datagatherer/eks/eks.go
  pkg/datagatherer/gke/gke.go
  pkg/datagatherer/k8s/generic.go
  pkg/datagatherer/local/local.go
Labels: approved, dco-signoff: yes, lgtm, size/M

#105 Change DataGatherers constructors to return DataGatherer interface
  pkg/datagatherer/aks/aks.go
  pkg/datagatherer/eks/eks.go
  pkg/datagatherer/gke/gke.go
  pkg/datagatherer/k8s/generic.go
  pkg/datagatherer/local/local.go
Labels: approved, dco-signoff: yes, lgtm, size/S

#106 Change PackageSource constructors to return PackageSource interface
  pkg/packagesources/local/local.go
Labels: approved, dco-signoff: yes, lgtm, size/XS

#107 Refactor output config
  cmd/check.go
  pkg/output/azblob/azblob.go
  pkg/output/cli/cli.go
  pkg/output/gcs/gcs.go
  pkg/output/local/local.go
  pkg/output/output.go
Labels: approved, dco-signoff: yes, lgtm, size/L

#108 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/document-research.md
  .github/ISSUE_TEMPLATE/package-suggestion.md
  .github/ISSUE_TEMPLATE/user-story.md
Labels: approved, dco-signoff: yes, lgtm, size/M

#110 Echo server to accept auth token
  cmd/echo.go
Labels: approved, dco-signoff: yes, lgtm, size/M

#104 Refactor config decoding in check function
  cmd/check.go
Labels: approved, dco-signoff: yes, lgtm, size/L

#111 Fix refactor config decoding in check function
  cmd/check.go
Labels: approved, dco-signoff: yes, lgtm, size/XS

#113 Agent to use auth token
  agent.yaml
  pkg/agent/run.go
Labels: approved, dco-signoff: yes, lgtm, size/S

#112 Move check config loading to own package
  cmd/check.go
  internal/checkconfig/checkconfig.go
Labels: approved, dco-signoff: yes, lgtm, size/XL

#115 Add GenReportMetadata function to Report
  api/report.go
Labels: approved, dco-signoff: yes, lgtm, size/S

#116 Fix typos in README.md
  README.md
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, size/XS

#120 Allow akvile to close issues
  OWNERS
Labels: approved, dco-signoff: yes, lgtm, size/XS

#122 Make other approvers reviewers
  OWNERS
Labels: approved, dco-signoff: yes, lgtm, size/XS

#119 Fix data-gatherers config loading
  agent.yaml
  pkg/agent/config.go
  pkg/agent/config_data_gatherers.go
  pkg/agent/config_data_gatherers_test.go
  pkg/agent/config_test.go
  pkg/agent/run.go
Labels: approved, dco-signoff: yes, lgtm, size/L

#121 Unmarshaler for k8s data-gatherer configuration
  pkg/datagatherer/k8s/generic.go
  pkg/datagatherer/k8s/generic_test.go
Labels: approved, dco-signoff: yes, lgtm, size/M

#123 Fix readme whitespace
  README.md
Labels: approved, dco-signoff: yes, lgtm, size/L

#124 k8s: allow setting KUBECONFIG to use via environment variable
  pkg/datagatherer/k8s/client.go
  pkg/datagatherer/k8s/client_test.go
Labels: approved, dco-signoff: yes, lgtm, size/L

#125 Explain data and permissions for all datagatherers
  agent.yaml
  docs/datagatherers/aks.md
  docs/datagatherers/eks.md
  docs/datagatherers/gke.md
  docs/datagatherers/k8s.md
  docs/datagatherers/k8s_pods.md
  docs/datagatherers/local.md
  examples/data/aks.json
  examples/data/gke.json
Labels: approved, dco-signoff: yes, lgtm, size/L

#126 Move sub-tasks to the end
  .github/ISSUE_TEMPLATE/user-story.md
Labels: approved, dco-signoff: yes, size/S
