Repository jetstack/jetstack-secure, pull requests merged in 2020-01, with the labels that each got.

#29 Package test command
  cmd/test.go
  go.mod
  go.sum
  pkg/packagesources/local/local.go
  pkg/packaging/eval.go
  pkg/packaging/packaging.go
  pkg/packaging/test.go
Labels: approved, dco-signoff: yes, lgtm, size/L

#34 Explain example preflight.yaml in image
  Dockerfile
Labels: approved, dco-signoff: yes, lgtm, size/M

#31 Update policy description
  examples/reports/pods.json
  preflight-packages/examples.jetstack.io/pods_basic/policy-manifest.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#35 Add Wil and Charlie to OWNERS
  OWNERS
Labels: approved, dco-signoff: yes, lgtm, size/XS

#33 Remove surplus iam member
  deployment/terraform/gke-datagatherer/googlecloud-scanner-serviceaccount.tf
  deployment/terraform/results-bucket/googlecloud-reports-bucket-scanner-sa.tf
Labels: approved, dco-signoff: yes, lgtm, size/XS

#32 Minor clarifications in cluster install pre-reqs
  docs/installation_manual_in_cluster.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#30 Add AKS data-gatherer
  cmd/check.go
  examples/aks.preflight.yaml
  go.mod
  go.sum
  pkg/datagatherer/aks/aks.go
  preflight-packages/examples.jetstack.io/aks_basic/aks.rego
  preflight-packages/examples.jetstack.io/aks_basic/policy-manifest.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XL

#28 Add manual to write packages
  docs/how_to_write_packages.md
  docs/images/preflight_package.png
Labels: approved, dco-signoff: yes, lgtm, size/L

#38 Show violations
  Makefile
  api/report.go
  cmd/test.go
  docs/how_to_write_packages.md
  pkg/exporter/json_test.go
  pkg/packaging/packaging.go
  pkg/results/results.go
  pkg/results/results_test.go
  preflight-packages/examples.jetstack.io/gke_basic/gke.rego
  preflight-packages/examples.jetstack.io/gke_basic/gke_test.rego
  preflight-packages/examples.jetstack.io/gke_basic/policy-manifest.yaml
  preflight-packages/examples.jetstack.io/pods_basic/pods.rego
  preflight-packages/examples.jetstack.io/pods_basic/pods_test.rego
Labels: approved, dco-signoff: yes, lgtm, size/XXL

#41 Update manual now that 'preflight package test' is a feature
  docs/how_to_write_packages.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#39 Add Make install target to facilitate version info in Docker
  Dockerfile
  Makefile
  go.sum
Labels: approved, dco-signoff: yes, lgtm, size/XS

#43 Update go mod sum file
  go.sum
Labels: approved, dco-signoff: yes, lgtm, size/XS

#44 Surface violations in report JSON
  api/report.go
  pkg/exporter/json.go
  pkg/exporter/json_test.go
Labels: approved, dco-signoff: yes, lgtm, size/S

#46 Change how results are unmarshaled from rego
  pkg/results/results.go
  pkg/results/results_test.go
Labels: approved, dco-signoff: yes, lgtm, size/S

#25 Do not enforce numeric IDs and enforce RootQuery
  cmd/lint.go
  pkg/lint/manifest.go
  pkg/lint/manifest_test.go
Labels: approved, dco-signoff: yes, lgtm, size/L

#47 Add pods package
  preflight-packages/examples.jetstack.io/pods_basic/pods.rego
  preflight-packages/examples.jetstack.io/pods_basic/pods_test.rego
  preflight-packages/examples.jetstack.io/pods_basic/policy-manifest.yaml
  preflight-packages/jetstack.io/pods/pods.rego
  preflight-packages/jetstack.io/pods/pods_test.rego
  preflight-packages/jetstack.io/pods/policy-manifest.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XXL

#50 Decrease package schema-version
  pkg/exporter/json_test.go
  pkg/lint/manifest_test.go
  preflight-packages/examples.jetstack.io/aks_basic/policy-manifest.yaml
  preflight-packages/examples.jetstack.io/gke_basic/policy-manifest.yaml
  preflight-packages/jetstack.io/pods/policy-manifest.yaml
Labels: approved, dco-signoff: yes, lgtm, size/S

#51 Add lint rule, update test rule, add both to CI test rule
  Makefile
  preflight-packages/examples.jetstack.io/aks_basic/aks.rego
  preflight-packages/examples.jetstack.io/aks_basic/aks_test.rego
Labels: approved, dco-signoff: yes, lgtm, size/M

#53 Replace sample pods package with full pods package in examples
  deployment/kubernetes/overlays/scanner/config/preflight.yaml
  examples/gke.preflight.yaml
  examples/pods.preflight.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#57 Update docs and README
  README.md
  docs/configuration.md
  docs/datagatherers/gke.md
  docs/datagatherers/k8s_pods.md
Labels: approved, dco-signoff: yes, lgtm, size/L

#60 Regenerate toc in readme
  README.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#61 Fix README markdown heading
  README.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#59 Handle the existence or not of the `preflight_` prefix in rego
  go.mod
  go.sum
  pkg/exporter/exporter.go
  pkg/exporter/exporter_test.go
  pkg/exporter/json.go
  pkg/exporter/json_test.go
  pkg/packaging/versioning.go
  pkg/packaging/versioning_test.go
Labels: approved, dco-signoff: yes, lgtm, size/L

#52 Add Azure Blob Storage option for the output
  cmd/check.go
  docs/configuration.md
  docs/images/azblob_keys.png
  examples/aks.preflight.yaml
  go.mod
  go.sum
  pkg/output/azblob/azblob.go
  pkg/output/gcs/gcs.go
Labels: approved, dco-signoff: yes, lgtm, size/L

#55 Update GKE basic package
  preflight-packages/examples.jetstack.io/gke_basic/gke.rego
  preflight-packages/examples.jetstack.io/gke_basic/gke_test.rego
  preflight-packages/examples.jetstack.io/gke_basic/policy-manifest.yaml
Labels: approved, dco-signoff: yes, lgtm, size/L

#62 Bump schema version for some packages
  preflight-packages/examples.jetstack.io/aks_basic/policy-manifest.yaml
  preflight-packages/jetstack.io/pods/policy-manifest.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#63 Extract report generation to reports package
  pkg/exporter/cli.go
  pkg/exporter/exporter.go
  pkg/exporter/json.go
  pkg/exporter/json_test.go
  pkg/exporter/markdown.go
  pkg/reports/reports.go
  pkg/reports/reports_test.go
  pkg/rules/rules.go
  pkg/rules/rules_test.go
Labels: approved, dco-signoff: yes, lgtm, size/L

#66 Report index constructors
  api/report.go
  pkg/reports/reports.go
  pkg/reports/reports_test.go
Labels: approved, dco-signoff: yes, lgtm, size/L

#71 Remove omit empty from violations
  api/report.go
Labels: approved, dco-signoff: yes, lgtm, size/XS

#69 Show schema-version on report
  api/report.go
  pkg/exporter/json_test.go
  pkg/reports/reports.go
  pkg/reports/reports_test.go
Labels: approved, dco-signoff: yes, lgtm, size/S

#68 Make command to fail if missing Rego definition
  cmd/check.go
  pkg/exporter/json.go
  pkg/exporter/json_test.go
  pkg/packaging/eval.go
  pkg/reports/reports.go
  pkg/reports/reports_test.go
Labels: approved, dco-signoff: yes, lgtm, size/L

#67 Allow disabling of rules in a package
  cmd/check.go
  pkg/packaging/eval.go
  pkg/packaging/packaging.go
  pkg/results/results.go
Labels: approved, dco-signoff: yes, lgtm, size/M

#70 Implement WriteIndex for cluster summaries
  cmd/check.go
  go.mod
  pkg/exporter/cli.go
  pkg/exporter/cli_test.go
  pkg/exporter/exporter.go
  pkg/exporter/html.go
  pkg/exporter/intermediate.go
  pkg/exporter/json.go
  pkg/exporter/json_test.go
  pkg/exporter/markdown.go
  pkg/exporter/markdown_test.go
  pkg/exporter/raw.go
  pkg/exporter/raw_test.go
  pkg/output/azblob/azblob.go
  pkg/output/cli.go
  pkg/output/gcs/gcs.go
  pkg/output/local.go
  pkg/output/output.go
Labels: approved, dco-signoff: yes, lgtm, size/XL

#72 Allow existing local indexes to be overwritten
  pkg/output/local.go
Labels: approved, dco-signoff: yes, lgtm, size/M
