Repository jetstack/jetstack-secure, pull requests merged in 2021-04, with the labels that each got.

#222 Use informers for dynamic datagatherers
  api/datareading.go
  api/datareading_test.go
  go.mod
  go.sum
  pkg/agent/dummy_data_gatherer.go
  pkg/agent/run.go
  pkg/datagatherer/aks/aks.go
  pkg/datagatherer/datagatherer.go
  pkg/datagatherer/eks/eks.go
  pkg/datagatherer/gke/gke.go
  pkg/datagatherer/istio/istio.go
  pkg/datagatherer/istio/istio_test.go
  pkg/datagatherer/k8s/cache.go
  pkg/datagatherer/k8s/cache_test.go
  pkg/datagatherer/k8s/discovery.go
  pkg/datagatherer/k8s/dynamic.go
  pkg/datagatherer/k8s/dynamic_test.go
  pkg/datagatherer/local/local.go
  pkg/datagatherer/versionchecker/versionchecker.go
  pkg/datagatherer/versionchecker/versionchecker_test.go
Labels: approved, dco-signoff: yes, do-not-merge/release-note-label-needed, size/XXL

#223 Move to Github actions and add support for arm
  .github/workflows/release-master.yml
  .github/workflows/release-tag.yml
  .github/workflows/test.yml
  Dockerfile
  Makefile
  builder.dockerfile
Labels: approved, dco-signoff: yes, do-not-merge/release-note-label-needed, size/L

#227 Use moby/buildkit:master when setting up buildx
  .github/workflows/release-master.yml
  .github/workflows/release-tag.yml
  .github/workflows/test.yml
Labels: approved, dco-signoff: yes, do-not-merge/release-note-label-needed, size/XS

#231 Use USER 1000:1000 in agent image.
  Dockerfile
Labels: approved, dco-signoff: yes, do-not-merge/release-note-label-needed, size/XS

#232 Switch to distroless/static base image
  Dockerfile
Labels: approved, dco-signoff: yes, do-not-merge/release-note-label-needed, size/XS
