Repository jetstack/jetstack-secure, pull requests merged in 2021-02, with the labels that each got.

#212 Load the period from config file
  cmd/agent.go
  pkg/agent/config.go
  pkg/agent/config_test.go
  pkg/agent/run.go
Labels: approved, dco-signoff: yes, do-not-merge/release-note-label-needed, size/S

#214 Remove install instructions
  README.md
Labels: approved, dco-signoff: yes, do-not-merge/release-note-label-needed, lgtm, size/L

#215 Use new auth server domain
  Makefile
Labels: approved, dco-signoff: yes, do-not-merge/release-note-label-needed, lgtm, size/XS

#216 Do not require period if one-shot mode
  pkg/agent/run.go
Labels: approved, dco-signoff: yes, do-not-merge/release-note-label-needed, lgtm, size/XS

#217 Change default config to be valid
  agent.yaml
Labels: approved, dco-signoff: yes, do-not-merge/release-note-label-needed, lgtm, size/XS

#218 Explain use of localServer in version checker dg
  pkg/datagatherer/versionchecker/versionchecker_test.go
Labels: approved, dco-signoff: yes, do-not-merge/release-note-label-needed, size/XS
