Repository jetstack/jetstack-secure, pull requests merged in 2021-06, with the labels that each got.

#234 Log when data is sent to the backend ok
  pkg/agent/run.go
Labels: approved, dco-signoff: yes, size/XS

#235 Update readme to refer to Jetstack Secure
  README.md
Labels: approved, dco-signoff: yes, size/M

#237 Add reference to Preflight in the Readme
  README.md
  docs/images/js.png
Labels: size/S
