Repository jetstack/jetstack-secure, pull requests merged in 2021-08, with the labels that each got.

#248 Add the compact flag
  cmd/echo.go
  pkg/echo/echo.go
Labels: size/M

#251 Remove auth token from echo server
  cmd/echo.go
  pkg/echo/echo.go
Labels: size/M

#252 Rbac generate
  pkg/agent/config.go
  pkg/agent/config_test.go
  pkg/permissions/generate.go
  pkg/permissions/generate_test.go
Labels: size/L

#254 Cluster role binding
  go.mod
  go.sum
  pkg/permissions/generate.go
  pkg/permissions/generate_test.go
Labels: size/L

#259 Update golang to 1.16
  builder.dockerfile
  go.mod
  go.sum
Labels: size/XS
