Repository jetstack/jetstack-secure, pull requests merged in 2023-06, with the labels that each got.

#444 Move oauth client code into client_oauth.go
  pkg/client/client.go
  pkg/client/client_oauth.go
Labels: size/L

#446 Add missing required fields to cert-manager example
  examples/cert-manager-agent.yaml
Labels: size/XS

#445 TLS Protect Cloud Authentication Addition
  agent.yaml
  cmd/agent.go
  go.mod
  go.sum
  pkg/agent/config.go
  pkg/agent/config_test.go
  pkg/agent/run.go
  pkg/client/client.go
  pkg/client/client_oauth.go
  pkg/client/client_venafi_cloud.go
Labels: size/XL
